# Generated by Django 5.0 on 2023-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinfo_poster_alter_director_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
